export const users = [
  {
    username: 'brawblan',
    password: 'Abc123!',
    firstName: 'Brandon',
    lastName: 'Blankenstein',
    address: '123 Street Drive',
    city: 'Austin',
    state: 'Texas',
    zipcode: '12345',
  },
  {
    username: 'jrad',
    password: 'sk8Rb0!',
    firstName: 'Jason',
    lastName: 'Brewer',
    address: '123 Street Drive',
    city: 'Austin',
    state: 'Texas',
    zipcode: '12345',
  },
  {
    username: 'markymark',
    password: 'n0Coff33!',
    firstName: 'Mark',
    lastName: 'Wahlbeck',
    address: '123 Street Drive',
    city: 'Austin',
    state: 'Texas',
    zipcode: '12345',
  },
  {
    username: 'bb',
    password: 'bb',
    firstName: '',
    lastName: '',
    address: '123 Street Drive',
    city: 'Austin',
    state: 'Texas',
    zipcode: '12345',
  },
]
